name: Auto approve PRs by dependabot

# Trigger the workflow on pull request
on: pull_request_target

jobs:
    approve:
        name: Approve dependabot PR
        runs-on: ubuntu-latest
        steps:
            - name: Auto approve
              uses: cognitedata/auto-approve-dependabot-action@v3.0.1
              if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    merge:
        - name: Merge dependabot PR
          uses: KeisukeYamashita/auto-pull-request-merge@v1
          with:
              intervalSeconds: 100
              timeoutSeconds: 30
              labels: ['dependencies']
